service: fiap-producao-ms 
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 512
  stage: prod
  disableRollback: true
  logs:
    httpApi: true
  # deploymentBucket:
  #   name: fiap-producao-ms-bucket
  #   versioning: true
  #   blockPublicAccess: true
  #   serverSideEncryption: AES256

plugins:
  # - serverless-deployment-bucket
  - serverless-s3-deploy

custom:
    assets:
      targets:
       - bucket: fiap-producao-ms-bucket
         files:
          - source: ./node_modules
            globs: '**/'
          - source: ./src/
            globs:
              - '**/'
          - source: ./dist/
            globs:
              - '**/'

  
functions:
  main:
    handler: dist/src/main.handler
    events:
      - httpApi:
          method: ANY
          path: /api-docs
      - httpApi:  
          method: ANY
          path: /api-docs/swagger-ui.css
      - httpApi:  
          method: ANY
          path: /api-docs/swagger-ui-bundle.js
      - httpApi:  
          method: ANY
          path: /api-docs/swagger-ui-standalone-preset.js
      - httpApi:  
          method: ANY
          path: /api-docs/swagger-ui-init.js
      - httpApi:
          method: PUT
          path: /producoes
      - httpApi:
          method: GET
          path: /producoes
      - httpApi:
          method: POST
          path: /producoes

package:
  patterns:
    - 'node_modules/**'
    - '!.serverless/**'
    - '!coverage/**'
    - 'dist/**'
    - '!.gitignore'
    - 'src/**'
    - "!.github"
    - '!.git/**'
    - '!terraform/**'
    - '!test/**'
    - '!report-config/**'
    - '!cucumber.js'
    - '!README.md'
    - '!features/**'
