service: fiap-producao-ms 
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x

functions:
  main:
    handler: dist/src/main.handler
    events:
      - httpApi:
          method: ANY
          path: /api-docs
      - httpApi:  
          method: ANY
          path: /api-docs/swagger-ui.css
      - httpApi:  
          method: ANY
          path: /api-docs/swagger-ui-bundle.js
      - httpApi:  
          method: ANY
          path: /api-docs/swagger-ui-standalone-preset.js
      - httpApi:  
          method: ANY
          path: /api-docs/swagger-ui-init.js
      - httpApi:
          method: PUT
          path: /producoes
      - httpApi:
          method: GET
          path: /producoes
      - httpApi:
          method: POST
          path: /producoes

package:
  patterns:
    - 'node_modules/**'
    - '!.serverless/**'
    - '!coverage/**'
    - 'dist/**'
    - '!.gitignore'
    - 'src/**'
    - "!.github"
    - '!.git/**'
    - '!terraform/**'
